# Generated by Django 5.1.1 on 2024-10-09 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('numero_os', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.loja')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.servico')),
            ],
        ),
    ]
